var json = {
  "years": [
    {
      "year": "2019",
      "months": [
        {
          "month": "January",
          "days": [
            {
              "day": "12 January 2019",
              "datas": [
                {
                  "duedate": "2 August 2019",
                  "project": "test",
                  "creditType": "test",
                  "document": "test",
                  "bgch": "1234",
                  "creditLine": "test",
                  "bank": "test",
                  "branch": "test",
                  "amount": "100000000"
                },
                {
                  "duedate": "3 August 2019",
                  "project": "test",
                  "creditType": "test",
                  "document": "test",
                  "bgch": "1234",
                  "creditLine": "test",
                  "bank": "test",
                  "branch": "test",
                  "amount": "50000000"
                }
              ]
            },
            {
              "day": "14 January 2019",
              "datas": [
                {
                  "duedate": "2 August 2019",
                  "project": "test",
                  "creditType": "test",
                  "document": "test",
                  "bgch": "1234",
                  "creditLine": "test",
                  "bank": "test",
                  "branch": "test",
                  "amount": "100000000"
                }
              ]
            },
          ]
        },
        {"month": "February"},
        {"month": "March"}
      ]
    },
    {
      "year": "2018",
      "months": [
        {
          "month": "January",
          "days": [
            {
              "day": "12 January 2018",
              "datas": [
                {
                  "duedate": "2 August 2018",
                  "project": "test",
                  "creditType": "test",
                  "document": "test",
                  "bgch": "1234",
                  "creditLine": "test",
                  "bank": "test",
                  "branch": "test",
                  "amount": "100000000"
                },
                {
                  "duedate": "3 August 2018",
                  "project": "test",
                  "creditType": "test",
                  "document": "test",
                  "bgch": "1234",
                  "creditLine": "test",
                  "bank": "test",
                  "branch": "test",
                  "amount": "50000000"
                }
              ]
            },
            {
              "day": "14 January 2018",
              "datas": [
                {
                  "duedate": "2 August 2018",
                  "project": "test",
                  "creditType": "test",
                  "document": "test",
                  "bgch": "1234",
                  "creditLine": "test",
                  "bank": "test",
                  "branch": "test",
                  "amount": "100000000"
                }
              ]
            },
          ]
        },
        {"month": "February"},
        {"month": "March"}
      ]
    }
  ]
};

var rawData = Autogenerated.fromJson(json);

//Class generated by https://javiercbk.github.io/json_to_dart/
class Autogenerated {
  List<Years> years;

  Autogenerated({this.years});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['years'] != null) {
      years = new List<Years>();
      json['years'].forEach((v) {
        years.add(new Years.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.years != null) {
      data['years'] = this.years.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Years {
  String year;
  List<Months> months;

  Years({this.year, this.months});

  Years.fromJson(Map<String, dynamic> json) {
    year = json['year'];
    if (json['months'] != null) {
      months = new List<Months>();
      json['months'].forEach((v) {
        months.add(new Months.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['year'] = this.year;
    if (this.months != null) {
      data['months'] = this.months.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Months {
  String month;
  List<Days> days;

  Months({this.month, this.days});

  Months.fromJson(Map<String, dynamic> json) {
    month = json['month'];
    if (json['days'] != null) {
      days = new List<Days>();
      json['days'].forEach((v) {
        days.add(new Days.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['month'] = this.month;
    if (this.days != null) {
      data['days'] = this.days.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Days {
  String day;
  List<Datas> datas;

  Days({this.day, this.datas});

  Days.fromJson(Map<String, dynamic> json) {
    day = json['day'];
    if (json['datas'] != null) {
      datas = new List<Datas>();
      json['datas'].forEach((v) {
        datas.add(new Datas.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['day'] = this.day;
    if (this.datas != null) {
      data['datas'] = this.datas.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Datas {
  String duedate;
  String project;
  String creditType;
  String document;
  String bgch;
  String creditLine;
  String bank;
  String branch;
  String amount;

  Datas(
      {this.duedate,
      this.project,
      this.creditType,
      this.document,
      this.bgch,
      this.creditLine,
      this.bank,
      this.branch,
      this.amount});

  Datas.fromJson(Map<String, dynamic> json) {
    duedate = json['duedate'];
    project = json['project'];
    creditType = json['creditType'];
    document = json['document'];
    bgch = json['bgch'];
    creditLine = json['creditLine'];
    bank = json['bank'];
    branch = json['branch'];
    amount = json['amount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['duedate'] = this.duedate;
    data['project'] = this.project;
    data['creditType'] = this.creditType;
    data['document'] = this.document;
    data['bgch'] = this.bgch;
    data['creditLine'] = this.creditLine;
    data['bank'] = this.bank;
    data['branch'] = this.branch;
    data['amount'] = this.amount;
    return data;
  }
}
